### ISSUE TITLE
SOLID. Redis

### ISSUE THREAD

**Issue by jrixs** [jrixs/geral_async_API_sprint_1#28]
Проверить класс по работе с кешом на SOLID. Изменить структуру программы, если это необходимо.

Оценка: 5

Ссылка на PR: pass

**Comment by Andrey12321** [comment]
Работа с Redis ведется в папке fastapi/src/services

В каждом классе сервиса есть put_film_to_cash и get_film_from_cash

1)каждый обработчик выполняет конкретную задачу
2)Код открыт для расширения, но закрыт для модификации
3)клиенты сервисов зависят только от тех методов, которые им действительно необходимы

А также выполняются Liskov Substitution Principle и Dependency Inversion Principle, поэтому код не нуждается в модификации
