### ISSUE TITLE
SOLID. Views

### ISSUE THREAD

**Issue by jrixs** [jrixs/geral_async_API_sprint_1#29]
Проверить класс по работе с бизнес-логикой на SOLID. Изменить структуру программы, если это необходимо.

Оценка: 8

Ссылка на PR: pass

**Comment by Andrey12321** [comment]
Разберем принципы Solid на данной задаче (код в папке fastapi/src/api/v1).

Single Responsibility Principle (SRP):
Каждый endpoint выполняет одну задачу: получение информации о фильме, жанре или персоне и получение их списков  Код разделен на логические части

Open-Closed Principle (OCP):
Код открыт для расширения, но закрыт для модификации. (Пример: чтобы добавить новые фильтры для поиска, можно просто изменить сигнатуры функций и внутреннюю логику). Использование сервисов для получения данных также способствует этому

Liskov Substitution Principle (LSP):
Принцип больше касается проектирования классов и наследования. Но сервисы используются в качестве зависимостей, что подразумевает возможность замены конкретных реализаций (например, FilmService или PersonService) другими, соответствующими тем же сервисам

Interface Segregation Principle (ISP):
В данном коде это принцип не применим напрямую, так как это не классы, а функции. Но использование различных сервисов помогает избегать "жирных" интерфейсов.

Dependency Inversion Principle (DIP):
Зависимости инвертированы с помощью Depends. Это делает код более гибким и тестируемым.

**Comment by Andrey12321** [comment]
Исходя из этого, код соответствует принципам Solid и в модификации не нуждается
