### ISSUE TITLE
Создать модели для фильмов и связанных данных

### ISSUE THREAD

**Issue by jrixs** [jrixs/geral_async_API_sprint_1#4]
Создать модели, прописав правильные типы данных для:

- фильмов,
- жанров,
- актеров, сценаристов, режиссеров.

Оценка: 5

**Comment by Andrey12321** [comment]
Для фильмов готово
для остального нужны страницы после ETL (предварительные версии готовы)

**Comment by Andrey12321** [comment]
closed
