### ISSUE TITLE
Создать схемы и таблицы в БД для сервиса auth.

### ISSUE THREAD

**Issue by jrixs** [jrixs/geral_async_API_sprint_1#62]
Создать схемы:
- auth_secret с таблицей auth
- auth_data с таблицами: 
   - user, 
   - role, 
   - permission

**Comment by cynimon** [comment]
Схема auth_secret

table Secrets
id
user_id (FK)
password (хэшированные данные)
updated_at (автоматическое поле)

Схема auth_data

table Users
id
username (по дефолту ставится обрезанное до @ имейла)
email
role_id (FK, мы предполагаем что у юзера может быть только одна роль, тк у нас есть гибкая настройка параметров ролей)
joined_at
updated_at

table History
id
user_id
last_logged_at
user_agent


Схема auth_service

table Roles
id
role_name
create_roles (boolean)
update_roles (boolean)
delete_roles (boolean)
check_user (boolean)
etc

table TokenSettings:
id
token (access/refresh)
time_alive (можем менять при необходимости время жизни токена)
